/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./components/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
    colors: {
      blueColor: "var(--blue-color)",
      indigoColor: "var(--indigo-color)",
      purpleColor: "var(--purple-color)",
      pinkColor: "var(--pink-color)",
      redColor: "var(--red-color)",
      orangeColor: "var(--orange-color)",
      yellowColor: "var(--yellow-color)",
      greenColor: "var(--green-color)",
      tealColor: "var(--teal-color)",
      cyanColor: "var(--cyan-color)",
      whiteColor: "var(--white-color)",
      grayColor: "var(--gray-color)",
      grayDarkColor: "var(--gray-dark-color)",
      primaryColor: "var(--primary-color)",
      primaryDarkColor: "var(--primary-dark-color)",
      secondaryColor: "var(--secondary-color)",
      successColor: "var(--success-color)",
      infoColor: "var(--info-color)",
      warningColor: "var(--warning-color)",
      dangerColor: "var(--danger-color)",
      lightColor: "var(--light-color)",
      darkColor: "var(--dark-color)",
      hoverLight: "var(--hover-light)",
    },
    screens: {
      'bXS': '0px',
      'bSM': '576px',
      'bMD': '768px',
      'bLG': '992px',
      'bXL': '1200px',
    },
  },
  plugins: [],
}
