export const packagesData = [
    {
        location: 'Thailand',
        duration: '5',
        capacity: '2',
        title: 'Discover amazing places of the world with us',
        averageReview: '4.6',
        totalReview: '72',
        price: '699',
        imageSrc: 'https://res.cloudinary.com/demo/image/fetch/https://i.ibb.co/N6Tqmrc/package-1.jpg',
    },
    {
        location: 'Spain',
        duration: '3',
        capacity: '1',
        title: 'Make your tour amazing with us',
        averageReview: '4.9',
        totalReview: '15',
        price: '450',
        imageSrc: 'https://res.cloudinary.com/demo/image/fetch/https://i.ibb.co/x1pnFRZ/package-2.jpg',
    },
    {
        location: 'Italy',
        duration: '15',
        capacity: '2',
        title: 'Dont\'t listen to what they say, go see',
        averageReview: '4.3',
        totalReview: '113',
        price: '1099',
        imageSrc: 'https://res.cloudinary.com/demo/image/fetch/https://i.ibb.co/SVryb2p/package-3.jpg',
    },
    {
        location: 'Greece',
        duration: '5',
        capacity: '2',
        title: 'Travel to make memories all around the world',
        averageReview: '4.5',
        totalReview: '48',
        price: '580',
        imageSrc: 'https://res.cloudinary.com/demo/image/fetch/https://i.ibb.co/8PKPg3d/package-4.jpg',
    },
    {
        location: 'New Zealand',
        duration: '2',
        capacity: '2',
        title: 'Make now your time to live the good life',
        averageReview: '4.7',
        totalReview: '250',
        price: '799',
        imageSrc: 'https://res.cloudinary.com/demo/image/fetch/https://i.ibb.co/tbThr1H/package-5.jpg',
    },
    {
        location: 'Australia',
        duration: '3',
        capacity: '2',
        title: 'Discover your right places with us',
        averageReview: '4.2',
        totalReview: '17',
        price: '479',
        imageSrc: 'https://res.cloudinary.com/demo/image/fetch/https://i.ibb.co/bXXffx8/package-6.jpg',
    },
]